module.exports = {
  caseType:'reconciled_salon_service_booking',
  initialState:'request_registered',
  states:['request_registered','availability_verified','price_confirmed','customer_approved','payment_authorized','scheduled','staff_assigned','in_progress','no_show','partial_service','service_exception','completed','refund_review','refunded','reconciled','closed'],
  createRoles:['booking_agent','location_manager'],
  assessmentRoles:['booking_agent','inventory_reviewer','location_manager'],
  auditRoles:['location_manager','finance_reviewer','auditor'],
  connectorRoles:['integration_operator','location_manager'],
  evidenceKinds:['service_request','availability_snapshot','pricing_tax_quote','inventory_snapshot','customer_consent','payment_authorization','schedule_receipt','staff_assignment','service_record','no_show_record','partial_service_record','exception_record','refund_approval','refund_receipt','accounting_reconciliation','notification_receipt'],
  requiredSignals:['availabilityVersion','pricingVersion','taxVersion','inventoryVersion','scheduleVersion','policyVersion','rightsStatus','consentStatus','availabilityStatus','priceStatus','inventoryStatus','paymentStatus','staffStatus'],
  professionalBoundary:'Assessment never books, charges, refunds, dispatches, or messages. Authorized location and finance staff approve consequential operations through credentialed systems.',
  connectors:[
    {name:'payment',purpose:'tokenized authorization, capture, and refund receipts'},
    {name:'tax',purpose:'versioned tax quote receipts'},
    {name:'inventory',purpose:'authoritative stock reservation receipts'},
    {name:'scheduling',purpose:'availability and reservation receipts'},
    {name:'messaging',purpose:'consented reminder receipts'},
    {name:'accounting',purpose:'settlement and reconciliation receipts'},
    {name:'delivery',purpose:'retail fulfillment receipts'},
    {name:'partner',purpose:'external service-provider receipts'},
  ],
  transitions:[
    {from:'request_registered',action:'verify_availability',to:'availability_verified',roles:['booking_agent','integration_operator'],requiresEvidence:true},
    {from:'availability_verified',action:'confirm_price',to:'price_confirmed',roles:['booking_agent'],requiresEvidence:true},
    {from:'price_confirmed',action:'record_customer_approval',to:'customer_approved',roles:['booking_agent'],requiresEvidence:true},
    {from:'customer_approved',action:'record_payment_authorization',to:'payment_authorized',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'payment_authorized',action:'record_schedule',to:'scheduled',roles:['booking_agent','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'scheduled',action:'assign_staff',to:'staff_assigned',roles:['location_manager'],requiresEvidence:true},
    {from:'staff_assigned',action:'start_service',to:'in_progress',roles:['service_provider','location_manager'],requiresEvidence:true},
    {from:'in_progress',action:'record_completion',to:'completed',roles:['service_provider','location_manager'],requiresEvidence:true},
    {from:'scheduled',action:'record_no_show',to:'no_show',roles:['booking_agent','location_manager'],requiresEvidence:true},
    {from:'in_progress',action:'record_partial_service',to:'partial_service',roles:['service_provider','location_manager'],requiresEvidence:true},
    {from:'in_progress',action:'record_exception',to:'service_exception',roles:['service_provider','location_manager'],requiresEvidence:true},
    {from:'no_show',action:'submit_refund_review',to:'refund_review',roles:['location_manager'],requiresEvidence:true},
    {from:'partial_service',action:'submit_refund_review',to:'refund_review',roles:['location_manager'],requiresEvidence:true},
    {from:'service_exception',action:'submit_refund_review',to:'refund_review',roles:['location_manager'],requiresEvidence:true},
    {from:'refund_review',action:'record_refund',to:'refunded',roles:['finance_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'completed',action:'record_reconciliation',to:'reconciled',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'refunded',action:'record_reconciliation',to:'reconciled',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'reconciled',action:'close_booking',to:'closed',roles:['location_manager'],requiresEvidence:true},
  ],
  acceptedFixture:{availabilityVersion:'a1',pricingVersion:'p1',taxVersion:'t1',inventoryVersion:'i1',scheduleVersion:'s1',policyVersion:'pol1',rightsStatus:'verified',consentStatus:'verified',availabilityStatus:'open',priceStatus:'accepted',inventoryStatus:'reserved',paymentStatus:'authorized',staffStatus:'available'},
  rejectedFixture:{availabilityVersion:'a1',pricingVersion:'p1',taxVersion:'t1',inventoryVersion:'i1',scheduleVersion:'s1',policyVersion:'pol1',rightsStatus:'verified',consentStatus:'verified',availabilityStatus:'conflict',priceStatus:'accepted',inventoryStatus:'reserved',paymentStatus:'authorized',staffStatus:'available'},
  readyDisposition:'location_and_finance_review_required',
  holdDisposition:'availability_payment_inventory_or_staff_hold',
  decisionField:'bookingCommand',
  assess:(x)=>{const ready=x.rightsStatus==='verified'&&x.consentStatus==='verified'&&x.availabilityStatus==='open'&&x.priceStatus==='accepted'&&x.inventoryStatus==='reserved'&&x.paymentStatus==='authorized'&&x.staffStatus==='available';return{disposition:ready?'location_and_finance_review_required':'availability_payment_inventory_or_staff_hold',bookingCommand:null,chargeCommand:null,versions:{availability:x.availabilityVersion,pricing:x.pricingVersion,tax:x.taxVersion,inventory:x.inventoryVersion,schedule:x.scheduleVersion}};},
};
